* Resumo
- No Brasil, houveram parcerias ostensivamente registradas com as seguintes GLAMs:
  + *2014*
    + Instituto Cultural Ítalo Brasileiro: digitalização do livro [[https://commons.wikimedia.org/wiki/Category:Il_Brasile_e_gli_Italiani][Il Brasile e gli Italiani]], com o suporte da empresa IAIDigital
  + *Maio de 2016*
    + [[https://commons.wikimedia.org/wiki/Category:Immigration_Museum_of_the_State_of_S%C3%A3o_Paulo][Museu da Imigração do Estado de São Paulo]]
  + *Agosto de 2016*
    + [[https://commons.wikimedia.org/wiki/Category:Collections_of_the_Museum_of_Veterinary_Anatomy_FMVZ_USP][Museu de Anatomia Veterinária da Faculdade de Medicina Veterinária e Zootecnia]] da Universidade de São Paulo
  + *Setembro de 2016*
    + [[https://commons.wikimedia.org/wiki/Category:Matemateca_IME-USP?uselang=pt-br][Matemateca]], Museu da Matemática da Universidade de São Paulo
    + [[https://commons.wikimedia.org/wiki/Category:Museu_da_Educa%C3%A7%C3%A3o_e_do_Brinquedo][Museu da Educação e do Brinquedo]] da Universidade de São Paulo

* Páginas notáveis
- [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter][This month in GLAM]]
- [[https://outreach.wikimedia.org/wiki/Category:This_Month_in_GLAM_Brazil_reports][Relatórios brasileiros]]
- [[https://outreach.wikimedia.org/wiki/GLAM/Case_studies/University_of_S%C3%A3o_Paulo_Museum_of_Veterinary_Anatomy/pt-br][Estudo de caso da Museu de Anatomia Veterinária da Universidade de São Paulo]]
- [[https://commons.wikimedia.org/wiki/Commons:Guide_to_batch_uploading][Contribuições em lotes na Wikimedia Commons]]

* This month in GLAM
A iniciativa voltada para GLAMs na Wikimedia mantém um boletim informativo sobre as atividades do grupo desde 2011 chamado [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter][This month in GLAM]] ("Neste mês, na GLAM" em tradução livre). Os seus volumes são anuais, com cada edição correspondendo a um mês do ano. Nessas edições, reúne-se informações tanto sobre iniciativas financiadas pela Wikimedia Foundation quanto voluntárias, iniciadas e mantidas por grupos locais  de wikimedistas. Os relatórios são apresentados por região (geralmente dividida em países) e por iniciativas "internacionais" (projetos como Wikidata, competições como Wiki Loves Monuments, equipes como  WMF [Wikimedia Foundation] GLAM, eventos em geral, entre outros assuntos considerados mundiais).

** Relatórios brasileiros

*** 2016

A atividade brasileira neste boletim começou a ser registrada em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/May_2016/Contents/Brazil_report][maio de 2016]], com um relatório sobre o progresso da política de acesso aberto do Museu da Imigração do Estado de São Paulo. Nele, afirma-se que o interesse na parceria nasceu do interesse de uma representante do museu, Juliana Monteiro, que participou do [[https://openpolicynetwork.org/iol/][Institute for Open Leardership 2]], treinamento sobre políticas de acesso aberto que aconteceu na Cidade do Cabo em março de 2016. Isso culminou na primeira colaboração do Museu da Imigração com a Wikimedia Commons, enviando ao acervo [[https://commons.wikimedia.org/wiki/Category:The_Path_of_the_Things_Exhibition_at_Immigration_Museum_of_the_State_of_S%C3%A3o_Paulo][componentes da exposição "O Caminho das Coisas"]]. Mais detalhes sobre essa experiência são descritos em sua postagem no blog da Creative Commons, [[https://creativecommons.org/2016/07/19/creative-commons-e-museu-da-imigracao-notas-sobre-experiencia-brasileira/][Creative Commons e Museu da Imigração: notas sobre uma experiência brasileira]].

No relatório de [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/June_2016/Contents/Brazil_report][junho]], afirma-se que a Wikimedia Foundation concedeu verba para remunerar uma pessoa por três meses para ajudar no fomento de parcerias entre GLAMs e projetos Wikimedia. Não há, entretanto, outras informações a respeito desta iniciativa em específico.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/July_2016/Contents/Brazil_report][julho]], o grupo de usuários brasileiros, junto ao COMCOL Brasil e a Tomara!, empresa de consultoria de projetos culturais, discutiram e desenvolveram uma proposta de projeto de mapeamento da performance de  museus de acordo com suas políticas de compartilhamento e uso de coleções na internet para um edital do estado de São Paulo.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/August_2016/Contents/Brazil_report][agosto]], anunciou-se uma parceria com o Museu de Anatomia Veterinária da Faculdade de Medicina Veterinária e Zootecnia da Universidade de São Paulo, com o apoio do Centro de Pesquisa, Inovação e Difusão em Neuromatemática (CEPID NeuroMat). Trata-se da primeira parceria com a USP. O mesmo relatório cita uma antiga parceria entre o grupo de usuários brasileiros e o Instituto Cultural Ítalo Brasileiro em 2014, em que o livro /Il Brasile e gli Italiani/ foi completamente digitalizado e hospedado na Wikimedia Commons. A digitalização foi feita com o apoio da empresa IAIDigital, especializada no segmento. 

Já em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/September_2016/Contents/Brazil_report][setembro]], os frutos dessa parceria começam a aparecer: a coleção se tornou notável entre wikipedistas, a ponto de inúmeras imagens serem nomeadas como algumas das mais valiosas na Wikimedia Commons. Uma maratona de edição foram realizadas para relacionar o conteúdo disponibilizado com as novas imagens. Wikipedistas da Wikipédia anglófona identificaram um erro de descrição em uma das peças. Outras GLAMs começam a entrar em contato com o grupo de usuários brasileiros. Sessenta manifestaram interesse, e parcerias com a Matemateca e o Museu da Educação e do Brinquedo foram estabelecidas.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/October_2016/Contents/Brazil_report][outubro]], o grupo brasileiro celebrou o fim da edição nacional da competição /Wiki Loves Monuments/ (Wiki ama monumentos, em tradução livre). Tal iniciativa convoca fotógrafos a imortalizarem monumentos de diversas cidades na Wikimedia Commons, ao mesmo tempo oferecendo premiações em dinheiro para os primeiros três lugares.

Também houve a realização da primeira edição do CCBWIKI (Congresso Científico Brasileiro da Wikipédia), na UNIRIO, entre os dias 13 e 14 de outubro, onde foi apresentado o progresso da iniciativa GLAM Wiki no Brasil.

Neste mês ainda, Juliana Monteiro e Edsonia Lopes se reuníram com três potenciais parceiros: o Instituto de Arte Contemporânea de São Paulo; a coordenação de imprensa e comunicação da Secretaria Municipal de São Paulo, que contribuiu bastante na promoção da competição /Wiki Loves Monuments/ e com quem se discutiu colaborações com museus sob a sua pasta; e com o diretor de Museologia da UNIRIO, com quem se discutiu um projeto sobre hereditariedade intangível.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/November_2016/Contents/Brazil_report][novembro]], a iniciativa com o Museu de Veterinária continuou a avançar, e a parceria com a Matemateca avançou — incluindo a compra de equipamentos específicos para este fim, financiados pela Wikimedia Foundation. Um [[https://outreach.wikimedia.org/wiki/GLAM/Case_studies/University_of_S%C3%A3o_Paulo_Museum_of_Veterinary_Anatomy/pt-br][estudo de caso]] sobre a parceria com o Museu de Veterinária foi publicado.

* Wiki Educação Brasil
