* Resumo
- No Brasil, houveram parcerias ostensivamente registradas com as seguintes GLAMs:
  + *Maio de 2016*
    + [[https://commons.wikimedia.org/wiki/Category:Immigration_Museum_of_the_State_of_S%C3%A3o_Paulo][Museu da Imigração do Estado de São Paulo]]
  + *Agosto de 2016*
    + [[https://commons.wikimedia.org/wiki/Category:Collections_of_the_Museum_of_Veterinary_Anatomy_FMVZ_USP][Museu de Anatomia Veterinária da Faculdade de Medicina Veterinária e Zootecnia]] da Universidade de São Paulo
  + *Setembro de 2016*
    + [[https://commons.wikimedia.org/wiki/Category:Matemateca_IME-USP?uselang=pt-br][Matemateca]], Museu da Matemática da Universidade de São Paulo
    + [[https://commons.wikimedia.org/wiki/Category:Museu_da_Educa%C3%A7%C3%A3o_e_do_Brinquedo][Museu da Educação e do Brinquedo]] da Universidade de São Paulo

* This month in GLAM
A iniciativa voltada para GLAMs na Wikimedia mantém um boletim informativo sobre as atividades do grupo desde 2011 chamado /This month in GLAM/ ("Neste mês, na GLAM" em tradução livre). Os seus volumes são anuais, com cada edição correspondendo a um mês do ano. Nessas edições, reúne-se informações tanto sobre iniciativas financiadas pela Wikimedia Foundation quanto voluntárias, iniciadas e mantidas por grupos locais  de wikimedistas. Os relatórios são apresentados por região (geralmente dividida em países) e por iniciativas "internacionais" (projetos como Wikidata, competições como Wiki Loves Monuments, equipes como  WMF [Wikimedia Foundation] GLAM, eventos em geral, entre outros assuntos considerados mundiais).

** Relatórios brasileiros

A atividade brasileira neste boletim começou a ser registrada em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/May_2016/Contents/Brazil_report][maio de 2016]], com um relatório sobre o progresso da política de acesso aberto do Museu da Imigração do Estado de São Paulo. Nele, afirma-se que o interesse na parceria nasceu do interesse de uma representante do museu, Juliana Monteiro, que participou do [[https://openpolicynetwork.org/iol/][Institute for Open Leardership 2]], treinamento sobre políticas de acesso aberto que aconteceu na Cidade do Cabo em março de 2016. Isso culminou na primeira colaboração do Museu da Imigração com a Wikimedia Commons, enviando ao acervo [[https://commons.wikimedia.org/wiki/Category:The_Path_of_the_Things_Exhibition_at_Immigration_Museum_of_the_State_of_S%C3%A3o_Paulo][componentes da exposição "O Caminho das Coisas"]]. Mais detalhes sobre essa experiência são descritos em sua postagem no blog da Creative Commons, [[https://creativecommons.org/2016/07/19/creative-commons-e-museu-da-imigracao-notas-sobre-experiencia-brasileira/][Creative Commons e Museu da Imigração: notas sobre uma experiência brasileira]].

No relatório de [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/June_2016/Contents/Brazil_report][junho de 2016]], afirma-se que a Wikimedia Foundation concedeu verba para remunerar uma pessoa por três meses para ajudar no fomento de parcerias entre GLAMs e projetos Wikimedia. Não há, entretanto, outras informações a respeito desta iniciativa em específico.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/August_2016/Contents/Brazil_report][agosto de 2016]], anunciou-se uma parceria com o Museu de Anatomia Veterinária da Faculdade de Medicina Veterinária e Zootecnia da Universidade de São Paulo, com o apoio do Centro de Pesquisa, Inovação e Difusão em Neuromatemática (CEPID NeuroMat). Trata-se da primeira parceria com a USP.

Já em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/September_2016/Contents/Brazil_report][setembro de 2016]], os frutos dessa parceria começam a aparecer: outras GLAMs começam a entrar em contato com o grupo de usuários brasileiros. Sessenta manifestaram interesse, e parcerias com a Matemateca e 

* Wiki Educação Brasil
