* Palavras a se evitar
** Obviamente, "todo mundo sabe que", "é fácil"...
Palavras ou expressões desnecessárias por serem:
- pouco descritivas.
- não acolhedoras (e se o que estivermos descrevendo não for tão óbvio ou lugar comum assim ao leitor?).
- não acrescentam valor algum.
** Basicamente
Trata-se de mais uma palavra comumente usada no discurso verbal para se ganhar tempo entre frases. Em um texto escrito, ela perde o seu valor. É melhor encurtar as sentenças, tornando-as mais claras, do que prolongá-las assim.
** "É claro que...", claramente
É melhor gastar energia explicando com palavras ou diagramas o que se diz do que afirmando que determinada coisa é clara.
** "É só...", "Só é preciso..."
Apesar de tornarem o discurso mais casual em algumas situações, também são expressões objetivamente desnecessárias.
** 
* Elementos visuais
** Capturas de tela
*** Apresentação de ferramentas
- Informar o usuário do contexto ao qual determinada ferramenta pertence é importante para que consiga se orientar de tela a tela. Portanto, antes de de introduzir instruções sobre uma determinada funcionalidade, apresente uma captura de tela da página que a contém.
- Ao invés de sinalizar cada ferramenta por algum tipo de indicativo visual na captura de tela de contexto geral, capture o ícone ou o menu correspondente de forma independente.
- A sequência de apresentação de elementos visuais em uma captura de tela, quando necessário listá-los, deve seguir a lógica natural de leitura — isto é, da esquerda para direita, de cima para baixo.
- As referências a itens da tela devem ser feitas com as suas denominações oficiais.
