* OAI-PMH
** Principais características
- Coleta e compartilhamento de metadados
- Baseada em padrões abertos (HTTP [Hypertext Transport Protocol] (para requisições) e XML [Extensible Markup Language]) (para respostas) -> aplicação rápida.
- Metadados coletados podem estar em qualquer formato definido pelas comunidades ou conjuntos de dados e provedores de serviço [que possa ser transformado em XML], mas Dublin Core[fn:1] simples[fn:2] é especificado para prover interoperabilidade mínina[fn:3].
  + Web & firewall friendly.
  + The Dublin Core Metadata Element Set: Title, Creator, Subject, Description, Publisher, Contributor, Date, Type, Format, Identifier, Source, Language, Relation, Coverage, Rights.
- Metadados de diferentes fontes podem ser reunidos em um só banco de dados, e serviços podem se utilizar desses dados agregados.
- O escopo do protocolo não comporta buscas (não há relação entre conteúdo e metadados)[fn:4] — só torna mais fácil a reunião de dados em um só lugar.
- Benefícios mais conhecidos: interoperabilidade de baixo custo, possibilidade de encontrar "recursos escondidos".

** Conceitos interessantes
1. *Provedor de dados vs. Provedor de serviços*
  + A arquitetura UPS [Universal Preprint Service], enquanto protótipo, designou estes dois papéis. Aqueles que lidam com o depósito e a publicação de dados referentes a recursos em repositórios, expondo os metadados à coleta, são os *provedores de dados*. Essas entidades são os criadores e os mantenedores dos metadados. Aqueles que coletam tais dados e oferecem serviços com os dados agregados são os *provedores de serviços*.

2. *Recursos*
  + Tudo que possui uma identidade. Um documento eletrônico, uma imagem, etc.

** Protocolo
*** Registro
Um registro tem três partes: cabeçalho, metadados e "sobre". Os dois primeiros são mandatórios.

**** Elementos do cabeçalho (obrigatório)
- identifier (mandatory: 1 only)
- datestamp (mandatory: 1 only)
- setSpec elements (optional: 0, 1 or more)
- status attribute for deleted item

**** Elementos dos metadados (obrigatório)
- XML encoded metadata with root tag, namespace
- repositories must support Dublin Core, may support other formats 

**** Elementos do "sobre" (opcional)
- rights statements
- provenance statements


[fn:1] Dublin Core Schema: conjunto de termos de vocabulário controlado usado para descrever recursos digitais e físicos.

[fn:2] ""Simple Dublin Core" is Dublin Core metadata that uses no qualifiers; only the main 15 elements of the Dublin Core Metadata Element Set are expressed as simple attribute-value pairs without any "qualifiers" (such as encoding schemes, enumerated lists of values, or other processing clues) to provide more detailed information about a resource." —  [[http://dublincore.org/resources/faq/][Dublin Core Frequently Asked Questions]]

[fn:3] "At a minimum, repositories must be able to return records with metadata expressed in the Dublin Core format, without any qualification." — [[http://www.openarchives.org/OAI/openarchivesprotocol.html#Record][OAI-PMH Specification 2.0]]

[fn:4] O protocolo deve ser usado com outros mecanismos para tal.
  
* ORCID
- Open Researcher and Contributor ID
- Atribui a cada pesquisador uma identidade única, em código alfanumérico, resolvendo problemas como os de nomes iguais, mudanças de nome legais, etc.

* Handle System
- https://en.wikipedia.org/wiki/Handle_System

* Linked Data...
- https://en.wikipedia.org/wiki/Linked_data

* ... com DBPedia
- https://en.wikipedia.org/wiki/DBpedia

* Padrões MARC
- https://en.wikipedia.org/wiki/MARC_standards

* LIDO
- https://en.wikipedia.org/wiki/LIDO

* SWORD
- https://en.wikipedia.org/wiki/SWORD_(protocol)

* Arquivos

** .JSON
- https://en.wikipedia.org/wiki/JSON

**
- https://wiki.duraspace.org/display/DSDOC6x/Importing+and+Exporting+Content+via+Packages

** 
- https://www.reviversoft.com/file-extensions/saf
