* Conceituação
Trata-se de um conjunto de regras que definem a forma como dois ou mais sistemas interagem entre si. 

* Importância
A escolha do protocolo certo é fundamental para aspectos como suporte a longo prazo e universalidade. A utilização de protocolos bem definidos a partir de especificações amplamente discutidas e acordadas é imprescindível para proporcionar compatibilidade entre sistemas e tornar processos mais ágeis.

* Alguns exemplos de protocolos presentes em nosso cotidiano
- HTTPS: protocolo utilizado para proporcionar segurança em comunicações feitas através de uma rede de computadores. Entre as razões para usá-lo estão a preocupação com a privacidade e a integridade dos dados compartilhados.

- Protocolo Signal: protocolo de encriptação ponta-a-ponta utilizado para tornar conversas em aplicativos como Signal e Whatsapp mais seguras.

* Lista de protocolos
** Para importar/exportar (upload/download de arquivos)
- Formato Tainacan
- Formato CSV
- Formato SAF
- Formato DIP Dspace
- RDF/OWL
- Formato EDM

** Via API
- Json
- OAI-PMH

** Futuros protocolos:
- ORCID
- Handle
- Linked Data com a DBpedia
- MARC
- LIDO
- SWORD

