* Resumo
- No Brasil, houveram parcerias ostensivamente registradas com as seguintes GLAMs:
  + *2014*
    + Instituto Cultural Ítalo Brasileiro: digitalização do livro [[https://commons.wikimedia.org/wiki/Category:Il_Brasile_e_gli_Italiani][Il Brasile e gli Italiani]], com o suporte da empresa IAIDigital
  + *Maio de 2016*
    + [[https://commons.wikimedia.org/wiki/Category:Immigration_Museum_of_the_State_of_S%C3%A3o_Paulo][Museu da Imigração do Estado de São Paulo]]
  + *Agosto de 2016*
    + [[https://commons.wikimedia.org/wiki/Category:Collections_of_the_Museum_of_Veterinary_Anatomy_FMVZ_USP][Museu de Anatomia Veterinária da Faculdade de Medicina Veterinária e Zootecnia]] da Universidade de São Paulo
  + *Setembro de 2016*
    + [[https://commons.wikimedia.org/wiki/Category:Matemateca_IME-USP?uselang=pt-br][Matemateca]], Museu da Matemática da Universidade de São Paulo
    + [[https://commons.wikimedia.org/wiki/Category:Museu_da_Educa%C3%A7%C3%A3o_e_do_Brinquedo][Museu da Educação e do Brinquedo]] da Universidade de São Paulo
  + *Outubro de 2017*
    + [[https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:Projetos/Arquivo_Nacional][Arquivo Nacional]]
  + *Novembro de 2017*
    + GLAM acessível: [[https://www.wikidata.org/wiki/Category:WikiProject_sum_of_all_paintings_in_Brazil][Museu Paulista, Museu Histórico Nacional, Museu Nacional de Belas Artes, Museu de Arte de São Paulo]]
    + [[https://commons.wikimedia.org/wiki/Category:NeuroMat%27s_partnership_with_Museu_Paulista_USP][Museu Paulista]]
  + *Fevereiro de 2018*
    + [[https://commons.wikimedia.org/wiki/Category:Media_contributed_by_the_Biblioteca_Brasiliana_Guita_e_Jos%C3%A9_Mindlin][Biblioteca Brasiliana Guita e José Mindlin]]
    + [[https://commons.wikimedia.org/wiki/Category:Media_contributed_by_the_National_Historical_Museum][Museu Histórico Nacional]]

* Páginas notáveis
- [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter][This month in GLAM]]
- [[https://outreach.wikimedia.org/wiki/Category:This_Month_in_GLAM_Brazil_reports][Relatórios brasileiros]]
- [[https://outreach.wikimedia.org/wiki/GLAM/Case_studies/University_of_S%C3%A3o_Paulo_Museum_of_Veterinary_Anatomy/pt-br][Estudo de caso da Museu de Anatomia Veterinária da Universidade de São Paulo]]
- [[https://commons.wikimedia.org/wiki/Commons:Guide_to_batch_uploading][Contribuições em lotes na Wikimedia Commons]]
- [[https://github.com/GLAMpipe/GLAMpipe][GLAMpipe]], uma ferramenta para visualizar, editar, baixar e enviar dados de GLAMs.
- [[Arquivo Nacional adere à Wiki Commons][Arquivo Nacional adere à Wiki Commons]]
- [[https://upload.wikimedia.org/wikipedia/commons/f/fa/Workshop_GLAM_Wiki_IWSC.pdf][GLAM: organização, incorporação e promoção de acervos nos projetos Wikimedia]]

* This month in GLAM
A iniciativa voltada para GLAMs na Wikimedia mantém um boletim informativo sobre as atividades do grupo desde 2011 chamado [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter][This month in GLAM]] ("Neste mês, na GLAM" em tradução livre). Os seus volumes são anuais, com cada edição correspondendo a um mês do ano. Nessas edições, reúne-se informações tanto sobre iniciativas financiadas pela Wikimedia Foundation quanto voluntárias, iniciadas e mantidas por grupos locais  de wikimedistas. Os relatórios são apresentados por região (geralmente dividida em países) e por iniciativas "internacionais" (projetos como Wikidata, competições como Wiki Loves Monuments, equipes como  WMF [Wikimedia Foundation] GLAM, eventos em geral, entre outros assuntos considerados mundiais).

** Relatórios brasileiros

*** 2016

A atividade brasileira neste boletim começou a ser registrada em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/May_2016/Contents/Brazil_report][maio de 2016]], com um relatório sobre o progresso da política de acesso aberto do Museu da Imigração do Estado de São Paulo. Nele, afirma-se que o interesse na parceria nasceu do interesse de uma representante do museu, Juliana Monteiro, que participou do [[https://openpolicynetwork.org/iol/][Institute for Open Leardership 2]], treinamento sobre políticas de acesso aberto que aconteceu na Cidade do Cabo em março de 2016. Isso culminou na primeira colaboração do Museu da Imigração com a Wikimedia Commons, enviando ao acervo [[https://commons.wikimedia.org/wiki/Category:The_Path_of_the_Things_Exhibition_at_Immigration_Museum_of_the_State_of_S%C3%A3o_Paulo][componentes da exposição "O Caminho das Coisas"]]. Mais detalhes sobre essa experiência são descritos em sua postagem no blog da Creative Commons, [[https://creativecommons.org/2016/07/19/creative-commons-e-museu-da-imigracao-notas-sobre-experiencia-brasileira/][Creative Commons e Museu da Imigração: notas sobre uma experiência brasileira]].

No relatório de [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/June_2016/Contents/Brazil_report][junho]], afirma-se que a Wikimedia Foundation concedeu verba para remunerar uma pessoa por três meses para ajudar no fomento de parcerias entre GLAMs e projetos Wikimedia. Não há, entretanto, outras informações a respeito desta iniciativa em específico.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/July_2016/Contents/Brazil_report][julho]], o grupo de usuários brasileiros, junto ao COMCOL Brasil e a Tomara!, empresa de consultoria de projetos culturais, discutiram e desenvolveram uma proposta de projeto de mapeamento da performance de  museus de acordo com suas políticas de compartilhamento e uso de coleções na internet para um edital do estado de São Paulo.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/August_2016/Contents/Brazil_report][agosto]], anunciou-se uma parceria com o Museu de Anatomia Veterinária da Faculdade de Medicina Veterinária e Zootecnia da Universidade de São Paulo, com o apoio do Centro de Pesquisa, Inovação e Difusão em Neuromatemática (CEPID NeuroMat). Trata-se da primeira parceria com a USP. O mesmo relatório cita uma antiga parceria entre o grupo de usuários brasileiros e o Instituto Cultural Ítalo Brasileiro em 2014, em que o livro /Il Brasile e gli Italiani/ foi completamente digitalizado e hospedado na Wikimedia Commons. A digitalização foi feita com o apoio da empresa IAIDigital, especializada no segmento. 

Já em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/September_2016/Contents/Brazil_report][setembro]], os frutos dessa parceria começam a aparecer: a coleção se tornou notável entre wikipedistas, a ponto de inúmeras imagens serem nomeadas como algumas das mais valiosas na Wikimedia Commons. Uma maratona de edição foram realizadas para relacionar o conteúdo disponibilizado com as novas imagens. Wikipedistas da Wikipédia anglófona identificaram um erro de descrição em uma das peças. Outras GLAMs começam a entrar em contato com o grupo de usuários brasileiros. Sessenta manifestaram interesse, e parcerias com a Matemateca e o Museu da Educação e do Brinquedo foram estabelecidas.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/October_2016/Contents/Brazil_report][outubro]], o grupo brasileiro celebrou o fim da edição nacional da competição /Wiki Loves Monuments/ (Wiki ama monumentos, em tradução livre). Tal iniciativa convoca fotógrafos a imortalizarem monumentos de diversas cidades na Wikimedia Commons, ao mesmo tempo oferecendo premiações em dinheiro para os primeiros três lugares.

Também houve a realização da primeira edição do CCBWIKI (Congresso Científico Brasileiro da Wikipédia), na UNIRIO, entre os dias 13 e 14 de outubro, onde foi apresentado o progresso da iniciativa GLAM Wiki no Brasil.

Neste mês ainda, Juliana Monteiro e Edsonia Lopes se reuníram com três potenciais parceiros: o Instituto de Arte Contemporânea de São Paulo; a coordenação de imprensa e comunicação da Secretaria Municipal de São Paulo, que contribuiu bastante na promoção da competição /Wiki Loves Monuments/ e com quem se discutiu colaborações com museus sob a sua pasta; e com o diretor de Museologia da UNIRIO, com quem se discutiu um projeto sobre hereditariedade intangível.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/November_2016/Contents/Brazil_report][novembro]], a iniciativa com o Museu de Veterinária continuou a avançar, e a parceria com a Matemateca avançou — incluindo a compra de equipamentos específicos para este fim, financiados pela Wikimedia Foundation. Um [[https://outreach.wikimedia.org/wiki/GLAM/Case_studies/University_of_S%C3%A3o_Paulo_Museum_of_Veterinary_Anatomy/pt-br][estudo de caso]] sobre a parceria com o Museu de Veterinária foi publicado.

Por fim, em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/December_2016/Contents/Brazil_report][dezembro]], o grupo brasileiro de usuários Wikimedia realizou um treinamento de difusão científica no NeuroMat, registrado [[https://pt.wikiversity.org/wiki/Treinamento_em_difus%C3%A3o_cient%C3%ADfica_web_2.0][nesta página da Wikiversidade]]; envios do Museu de Veterinária da USP com uma ferramenta chamada [[https://meta.wikimedia.org/wiki/Grants:Project/Susannaanas/GLAMpipe][GLAMpipe]], recém-desenvolvida por wikimedistas finlandeses; e encontros com a Fundação Energia e Saneamento de São Paulo, interessados em expandir artigos relacionados a museus, e com a Escola de Museologia da UNIRIO, para criar dois grupos de estudo. Com o último, houve a criação e o aprimoramento de vários artigos, como o do autor Zbyněk Zbyslav Stránský.

Sob a tutela de Juliana Monteiro, alunos de Museologia da ETEC Parque Juventude produziram textos e fotografias para a Wikimedia Commons sobre os museus Dom Pedro I and Dona Leopoldina, em Pindamonhangaba; Museu Histórico Paulo Setúbal, em Tatuí; Museu Visconde de Mauá, em Mogi das Cruzes; e o Museu Prudente de Morais, em Piracicaba. Aproveitando a oportunidade, eles começaram a explorar a possibilidade de inclusão de GLAMs brasileiras na Wikidata, sendo os primeiros a serem inseridos as GLAMs Pinacoteca do Estado de São Paulo, Museu da Casa Brasileira, Museu Afro Brasil e Museu Cada de Portinari.

Por último, fizeram uma lista de autores e obras que entram em domínio público em 2017 para celebrá-los no Dia do Domínio Público e fazer as suas obras disponíveis da Wikimedia Commons.

*** 2017

Os relatórios começam em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/January_2017/Contents/Brazil_report][janeiro]], falando sobre divulgação de livros em domínio público no Dia do Domínio Público, possíveis parcerias com o Museu de Saúde Pública Emílio Ribas e uma maratona de edições a ser realizada em conjunto com o COMCOL e a Superintendência de Museus da Secretaria Municipal da Cultura do Rio de Janeiro.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/February_2017/Contents/Brazil_report][fevereiro]], anunciou-se o diálogo entre o grupo de usuários brasileiros e o Museu do Futebol de São Paulo, que colaborou com artigos no evento Edit-a-thon BBC 100 Women e expressou interesse em aprimorar o conteúdo na Wikipédia. Também se reportou o sucesso da primeira maratona de edições voltada para museus no Rio de Janeiro, que buscou educar profissionais sobre acesso aberto e apresentá-los às iniciativas Wikimedia.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/April_2017/Contents/Brazil_report][abril]], noticia-se a [[https://meta.wikimedia.org/wiki/Wiki_Education_Brazil/Projects/GLAM_Museu_de_Sa%C3%BAde_P%C3%BAblica_Em%C3%ADlio_Ribas#Equipe%7C][primeira sessão de treinamento]] com o Museu de Saúde Pública Emílio Ribas.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/May_2017/Contents/Brazil_report][maio]], fala-se sobre esforços para recrutar novos voluntários e uma maratona de edição realizado do Museu da Imigração do Estado de São Paulo. Tal maratona foi parte da programação da 15ª Semana Nacional de Museus, patrocinada pelo IBRAM.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/August_2017/Contents/Brazil_report][agosto]], reportou-se diversas atividades realizadas por Wilson Krugner Vicentim, wikipedista em residência no Centro de Pesquisa, Inovação e Difusão em Neuromatemática (CEPID NeuroMat). Suas ações se concentraram principalmente na promoção de maratonas de edição para aprimorar artigos da Wikipédia relacionados à matemática.

Também foi anunciada a conclusão do trabalho desenvolvido com alunos de Museologia da ETEC Parque Juventude.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/October_2017/Contents/Brazil_report][outubro]], o grupo lançou um [[https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:Projetos/Arquivo_Nacional][projeto interwikis]] com o Arquivo Nacional. O relatório descreve como atividades principais:

- Curadoria de categorias dos arquivos enviados à Commons
- Identificação de lugares e pessoas retratados em fotografias
- Transcrição de documentos na Wikisource
- Aprimoramento de conteúdo na Wikipédia
- Aprimoramento de conteúdo na Wikidata.

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/November_2017/Contents/Brazil_report][novembro]], lançou-se um projeto focada em acessibilidade tendo como objetos principais os quadros do Museu Paulista (marjoritariamente), Museu Histórico Nacional, Museu Nacional de Belas Artes e Museu de Arte de São Paulo. Consiste em audiodescrever quadros notáveis, tornando-os acessíveis a deficientes visuais. Esse processo foi realizado por alunos da Faculdade Cásper Líbero e revisado por profissionais e estudantes da Laramara (Associação Brasileira de Assistência à Pessoa com Deficiência Visual).

Também foi realizado o 2º CCBWIKI e o 1º IWSC (Conferência Científica Internacional da Wikipédia) em Niterói. Uma oficina sobre GLAMs foi realizada pela equipe encarregada dos projetos.

Enfim, começou-se um projeto de [[https://commons.wikimedia.org/wiki/Category:GLAM_3D_reconstructions_by_Cicero_Moraes][reconstrução 3D com o design gráfico Cícero Moraes]]. A ideia é fornecer à Wikimedia Commons reconstruções de figuras notáveis.

*** 2018

As iniciativas começam a ser reportadas em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/February_2018/Contents/Brazil_report][fevereiro]], com o anúncio de uma parceria formal com a [[https://commons.wikimedia.org/wiki/Category:Media_contributed_by_the_Biblioteca_Brasiliana_Guita_e_Jos%C3%A9_Mindlin][Biblioteca Brasiliana Guita e José Mindlin]] e o [[https://commons.wikimedia.org/wiki/Category:Media_contributed_by_the_National_Historical_Museum][Museu Histórico Nacional]].

Em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/April_2018/Contents/Brazil_report][abril]], reportou-se inúmeras oficinas focadas em divulgar a capacidade e utilidade da Wikidata, além de suas possibilidades de integração com outros projetos como Wikipédia.

Por fim, em [[https://outreach.wikimedia.org/wiki/GLAM/Newsletter/May_2018/Contents/Brazil_report][maio]], foi lançado o [[https://pt.wikipedia.org/wiki/Wikip%C3%A9dia:GLAM/Museu_Paulista][novo portal do Museu Paulista]], finalizados os últimos envios da Matemateca, e comemorado o impacto do acervo do Arquivo Nacional — com 16 milhões de visualizações somente em maio, ele se tornou o mais visto dos mantidos pelo grupo brasileiro.

