* Primeiro dia
** Manhã
- Introdução dos participantes da oficina
  + *Perguntas importantes:* Quais são as suas necessidades? Como você chegou à ferramenta? Com que tipo de conteúdo você trabalha?
- Apresentação da ferramenta: conceitos-chave, panorama dos acervos digitais
  + Por que não falar sobre licenças e conhecimento aberto?
** Tarde
- Exploração da ferramenta
  + *Questões importantes:* Que tal incentivar o uso de bibliotecas com licenças livres?
  + *Problemas:* Convém testar (1) as máquinas que serão usadas para a capacitação — muitas apresentaram problemas de software e hardware, (2) a conexão WiFi — houve muitas quedas e problemas de funcionamento, (3) a instalação do Tainacan a ser usada na formação — encontrou-se muitos problemas de nagevação.
* Segundo dia
** Manhã
- Continuação da exploração da ferramenta
  + Alguns dos caminhos de modificação da coleção são muito longos, pouco intuitivos e confusos.
  + *Sugestão:* Quando criar categorias ou subcategorias, poder criar mais de uma por vez.
  + *Crítica:* Processo de adição à categorias é muito lento.
  + *Sugestão:* Estudo da turma — saber que conceitos ela domina, e com quais ela tem dificuldades. Compor uma biblioteca de mídias (com vários tipos de formatos) para exemplificar todos os caminhos e possibilidades, conforme necessidades dos atendentes. Moldar a apresentação levando em conta o perfil da turma.
  + *Sugestão:* Como organizar as coleções? Adicionar uma seção da oficina para isso pode ser benéfico.
